services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build:
       context: ./requirements/mariadb
       dockerfile: Dockerfile
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - network
    restart: always
    expose:
      - 3306
  
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - network
    restart: always
    expose:
      - 9000
  
  nginx:
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - network
    restart: always
    ports:
      - "443:443"

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: /home/thunlos/db-data
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: /home/thunlos/wordpress-data
      o: bind

networks:
  network: {}