services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build:
       context: ./requirements/mariadb
       dockerfile: Dockerfile
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - network
    restart: on-failure
    expose:
      - 3306

  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - network
    restart: on-failure
    expose:
      - 6379
  
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - network
    restart: on-failure
    expose:
      - 9000

  adminer:
    container_name: adminer
    env_file:
      - .env
    depends_on:
      - mariadb
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    networks:
      - network
    volumes:
      - wordpress-data:/var/www/html
    restart: on-failure
    expose:
      - 9000
  
  nginx:
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress
      - adminer
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - network
    restart: on-failure
    ports:
      - "443:443"
  
  ftp:
    container_name: ftp
    env_file:
      - .env
    depends_on:
      - wordpress
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - network
    restart: on-failure
    ports:
      - "20:20"
      - "21:21"
  
  eleventy:
    container_name: eleventy
    build:
      context: ./requirements/bonus/eleventy
      dockerfile: Dockerfile
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - network
    restart: on-failure
    ports:
      - "8080:8080"

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: /home/psalame/db-data
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: /home/psalame/wordpress-data
      o: bind

networks:
  network: {
    driver: bridge
  }